name: github_poc
description: A POC for GitHub API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  auto_route: ^10.1.2
  bloc: ^9.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mocktail: ^1.0.4
  retrofit: ^4.7.2
  url_launcher: ^6.3.0

dev_dependencies:
  auto_route_generator: ^10.2.4
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.0
  mocktail: ^1.0.4
  retrofit_generator: ^10.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
